"""Add linkedin_content and twitter_thread fields to Post model

Revision ID: f3f078aed823
Revises: accffe43b77d
Create Date: 2025-10-24 08:41:10.588119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f078aed823'
down_revision = 'accffe43b77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('twitter_thread', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('twitter_thread')
        batch_op.drop_column('linkedin_content')

    # ### end Alembic commands ###
