from flask import request, jsonify
from flask_login import login_required, current_user
from . import bp
from ..extensions import limiter


@bp.post('/summarize')
@limiter.limit('5/minute;100/day')
@login_required
def summarize():
	post_id = request.json.get('post_id') if request.is_json else None
	if not post_id:
		return jsonify({'error': 'post_id required'}), 400
	# Placeholder response
	return jsonify({'summary': 'Summary will be generated by AI service.'})


@bp.post('/blog-to-linkedin')
@limiter.limit('5/minute;100/day')
@login_required
def blog_to_linkedin():
	post_id = request.json.get('post_id') if request.is_json else None
	if not post_id:
		return jsonify({'error': 'post_id required'}), 400
	return jsonify({'text': 'LinkedIn-formatted text will appear here.'})


@bp.post('/blog-to-twitter-thread')
@limiter.limit('5/minute;100/day')
@login_required
def blog_to_twitter_thread():
	post_id = request.json.get('post_id') if request.is_json else None
	if not post_id:
		return jsonify({'error': 'post_id required'}), 400
	return jsonify({'tweets': ['Tweet 1', 'Tweet 2']})
